name: flutter_application
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  bloc: ^9.2.0
  build_runner: ^2.15.0
  carousel_slider: ^5.1.2
  cloud_firestore: ^6.3.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  equatable: ^2.0.8
  firebase_app_check: ^0.4.3
  firebase_auth: ^6.4.0
  firebase_core: ^4.7.0
  firebase_messaging: ^16.4.1
  firebase_storage: ^13.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^22.0.1
  flutter_native_splash: ^2.4.7
  flutter_screenutil: ^5.9.3
  flutter_stripe: ^13.0.0
  flutter_svg: ^2.2.2
  freezed: ^3.2.5
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  get_it: ^9.2.1
  google_sign_in: ^6.2.1
  hive_flutter: ^1.1.0
  ionicons: ^0.2.2
  json_annotation: ^4.12.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.14.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/homePhoto/
    - assets/images/icons/
    - assets/images/cover/
    - assets/images/banners/

  fonts:
    - family: "TenorSans"
      fonts:
        - asset: assets/fonts/Tenor_Sans/TenorSans-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/homePhoto/icon.png"
  min_sdk_android: 21
