// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

//
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAga6_B93zIfCdi1Z1Zq6dcQpypyr37mQs',
    appId: '1:805763970676:web:2bdd2b2127a69358078321',
    messagingSenderId: '805763970676',
    projectId: 'fashon-app-5cd82',
    authDomain: 'fashon-app-5cd82.firebaseapp.com',
    databaseURL: 'https://fashon-app-5cd82-default-rtdb.firebaseio.com',
    storageBucket: 'fashon-app-5cd82.firebasestorage.app',
    measurementId: 'G-QGTZEFV3KB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFd_doZvWl0VQ3job_wcXrqebjgyQvBzY',
    appId: '1:805763970676:android:8ac47b1b6cc59815078321',
    messagingSenderId: '805763970676',
    projectId: 'fashon-app-5cd82',
    databaseURL: 'https://fashon-app-5cd82-default-rtdb.firebaseio.com',
    storageBucket: 'fashon-app-5cd82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy70_RiDOvwQZGLOhEpAWlKgwdYq46E2Q',
    appId: '1:805763970676:ios:403f17e35e18a803078321',
    messagingSenderId: '805763970676',
    projectId: 'fashon-app-5cd82',
    databaseURL: 'https://fashon-app-5cd82-default-rtdb.firebaseio.com',
    storageBucket: 'fashon-app-5cd82.firebasestorage.app',
    androidClientId:
        '805763970676-uu4ie3cgm1f5hsesqh715do4kk03t2bn.apps.googleusercontent.com',
    iosClientId:
        '805763970676-5s32e3r2u4log0tba3qi7kqfe3ie2stf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy70_RiDOvwQZGLOhEpAWlKgwdYq46E2Q',
    appId: '1:805763970676:ios:403f17e35e18a803078321',
    messagingSenderId: '805763970676',
    projectId: 'fashon-app-5cd82',
    databaseURL: 'https://fashon-app-5cd82-default-rtdb.firebaseio.com',
    storageBucket: 'fashon-app-5cd82.firebasestorage.app',
    androidClientId:
        '805763970676-uu4ie3cgm1f5hsesqh715do4kk03t2bn.apps.googleusercontent.com',
    iosClientId:
        '805763970676-5s32e3r2u4log0tba3qi7kqfe3ie2stf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAga6_B93zIfCdi1Z1Zq6dcQpypyr37mQs',
    appId: '1:805763970676:web:5aeb7f88c7295ba8078321',
    messagingSenderId: '805763970676',
    projectId: 'fashon-app-5cd82',
    authDomain: 'fashon-app-5cd82.firebaseapp.com',
    databaseURL: 'https://fashon-app-5cd82-default-rtdb.firebaseio.com',
    storageBucket: 'fashon-app-5cd82.firebasestorage.app',
    measurementId: 'G-0XTZHBD4XN',
  );
}
